# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.5.1"
StyLua = "JohnnyMorganz/StyLua@2.1.0"
selene = "Kampfkarren/selene@0.28.0"
lune = "lune-org/lune@0.8.9"
luau-lsp = "JohnnyMorganz/luau-lsp@1.49.0"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
